apiVersion: kubeadm.k8s.io/v1beta2
imageRepository: registry.aliyuncs.com/google_containers
kind: ClusterConfiguration
kubernetesVersion: v1.20.0
controllerManager:
  extraArgs:
    horizontal-pod-autoscaler-sync-period: 10s
    node-monitor-grace-period: 10s
apiServer:
  extraArgs:
    runtime-config: api/all=true
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cgroup-driver: "systemd"
